# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('primary_number', models.CharField(max_length=255)),
                ('secondary_number', models.CharField(blank=True, default=None, max_length=255)),
                ('business_email', models.CharField(max_length=255)),
                ('website', models.CharField(blank=True, default=None, max_length=255)),
                ('facebook', models.CharField(blank=True, default=None, max_length=255)),
                ('twitter', models.CharField(blank=True, default=None, max_length=255)),
                ('instagram', models.CharField(blank=True, default=None, max_length=255)),
                ('yelp', models.CharField(blank=True, default=None, max_length=255)),
                ('pending', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('primary_number', models.CharField(max_length=255)),
                ('primary_contact', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('starting_date', models.CharField(max_length=255)),
                ('ending_date', models.CharField(max_length=255)),
                ('pending', models.BooleanField(default=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to='adinba_app.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('starting_date', models.CharField(max_length=255)),
                ('ending_date', models.CharField(max_length=255)),
                ('pending', models.BooleanField(default=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials_host', to='adinba_app.Business')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('primary_number', models.CharField(blank=True, default=None, max_length=255)),
                ('secondary_number', models.CharField(blank=True, default=None, max_length=255)),
                ('business_owner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='special',
            name='users',
            field=models.ManyToManyField(related_name='claimee', to='adinba_app.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(related_name='attendee', to='adinba_app.User'),
        ),
        migrations.AddField(
            model_name='business',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='adinba_app.User'),
        ),
    ]
